# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20160623_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporyProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=150)),
                ('image', models.FileField(upload_to=b'images/tempory/')),
            ],
        ),
    ]
