# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_temporyproductimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporyproductimage',
            name='fileName',
            field=models.CharField(default='a', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='temporyproductimage',
            name='image',
            field=models.FileField(upload_to=product.models.generate_temp_image_filename),
        ),
    ]
