# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20160628_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='fileName',
            field=models.CharField(default='a', max_length=150),
            preserve_default=False,
        ),
    ]
