# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productimage_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='postedDate',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
