# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_posteddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contactNumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
