# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_selectproductattributevalues_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='showIcons',
            field=models.BooleanField(),
            preserve_default=False,
        ),
    ]
