# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_productattribute_showicons'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDataSelectValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='productdata',
            name='selectValues',
            field=models.ManyToManyField(blank=True, null=True, to='product.SelectProductAttributeValues'),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='value',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productdataselectvalue',
            name='productData',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductData'),
        ),
        migrations.AddField(
            model_name='productdataselectvalue',
            name='selectValue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SelectProductAttributeValues'),
        ),
    ]
