# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_productdata_selectvalues'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='searchByOr',
            field=models.BooleanField(),
            preserve_default=False,
        ),
    ]
